### ISSUE TITLE
Do you know why your package 29ms to startup?

### ISSUE THREAD

**Issue by olivierlacan** [primitive-type/update-packages#1]
I've noticed that most packages only add a handful milliseconds to startup time, I'm curious if you know why this one adds so much more?

![image](https://f.cloud.github.com/assets/65950/2428652/640e3b98-ac55-11e3-86ae-2ed851f48548.png)

Especially when update-package-dependencies only adds 2ms:

![image](https://f.cloud.github.com/assets/65950/2428657/94fcbaea-ac55-11e3-8ba2-74c861fc6c1c.png)

For reference tree-view adds a ton more, not sure why either but it seems like it has more impact on the editor overall:

![image](https://f.cloud.github.com/assets/65950/2428655/7a58280a-ac55-11e3-9017-742a6ad2db97.png)

**Comment by primitive-type** [comment]
@olivierlacan Do these times, on average, consistently recur for you, or was it just a handful of startups where you noticed this?

On my end, closing and reopening Atom three times consecutively, this package added 3ms, 4ms, and 3ms to startup time, respectively. 

I would like to be able to see what is used in the Atom editor to measure this time, and if there are any suggested ways of going about optimization. I'm also not quite sure what exactly is performed at the per-package level upon startup. In general, package startup times seem to be highly variable on my end. For example, on one startup Tree View added 433ms, and the next one yielded only an additional 19ms. I think there are a lot of variables at play that can influence the stat. If I figure out ways to optimize startup time, I will certainly apply them here.

**Comment by olivierlacan** [comment]
@primitive-type You're absolutely correct. I just opened Atom and it's down to 1ms. We should probably report this on [discuss.atom.io](http://discuss.atom.io).
