### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by fabiusss** [primitive-type/update-packages#2]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.

```
Atom.Object.defineProperty.get (C:\Users\Fabiano\AppData\Local\atom\app-0.181.0\resources\app\src\atom.js:54:11)
Object.activate (C:\Users\Fabiano\.atom\packages\update-packages\lib\update-packages.coffee:6:9)
```

**Comment by primitive-type** [comment]
I've unpublished this package. Please see https://github.com/primitive-type/update-packages/issues/5
