### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by fundor333** [primitive-type/update-packages#3]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.

```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
Object.activate (/Users/f333/.atom/packages/update-packages/lib/update-packages.coffee:6:9)
```

**Comment by primitive-type** [comment]
I've unpublished this package. Please see https://github.com/primitive-type/update-packages/issues/5
